allowBuilds:
  puppeteer: true
  unrs-resolver: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vitest: 4.1.10
  vite-plus: 0.2.9
  "@vitest/coverage-v8": 4.1.10
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
  minimatch: ">=3.1.4"
nodeVersion: 22.22.3
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-*"
  - vite-plus
