allowBuilds:
  puppeteer: true
  unrs-resolver: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
  minimatch: ">=3.1.4"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
