allowBuilds:
  puppeteer: true
  unrs-resolver: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vitest: 5.0.1
  vite-plus: 1.0.0
  "@vitest/coverage-v8": 5.0.1
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
  minimatch: ">=3.1.4"
nodeVersion: 22.22.3
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-*"
  - vite-plus
